### ISSUE TITLE
Small typo in the daemon's exec file

### ISSUE THREAD

**Issue by SartoRiccardo** [turingarena/turingarena#48]
While typing `sudo turingarenad` I stumbled upon this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/turingarenad", line 7, in <module>
    from turingarena_daemon import turingarena_daemon
ImportError: No module named 'turingarena_daemon'
```
I looked at the file and the 7th line says
`from turingarena_daemon import turingarena_daemon`

I tried some combinations and it seemed to work with the following line:
`from turingarena_cli import turingarena_daemon`

It's probably just a small typo, just wanted to let you know!

**Comment by alerighi** [comment]
I've done some modification, I moved the daemon into a separate file. You should run again setup.py in the cli directory, and the it should work again. 

Let me know if this fixes the issue.

**Comment by SartoRiccardo** [comment]
I ran the command `sudo python3 setup.py install` but it still gives the same error, except now it's on line 6 instead of 7. Here was the output:
```
/home/riccardo/turingarena/cli/.eggs/pbr-4.1.0-py3.5.egg/pbr/core.py:120: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/riccardo/turingarena/cli/.eggs/pbr-4.1.0-py3.5.egg/pbr/core.py:120: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.1s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.2s)
running build
running build_py
running egg_info
writing pbr to turingarena_cli.egg-info/pbr.json
writing top-level names to turingarena_cli.egg-info/top_level.txt
writing turingarena_cli.egg-info/PKG-INFO
writing entry points to turingarena_cli.egg-info/entry_points.txt
writing dependency_links to turingarena_cli.egg-info/dependency_links.txt
[pbr] Reusing existing SOURCES.txt
running install_lib
running install_egg_info
removing '/usr/local/lib/python3.5/dist-packages/turingarena_cli-0.0.1.dev1384.egg-info' (and everything under it)
Copying turingarena_cli.egg-info to /usr/local/lib/python3.5/dist-packages/turingarena_cli-0.0.1.dev1384.egg-info
running install_scripts
Installing turingarena script to /usr/local/bin
Installing turingarena_new script to /usr/local/bin
Installing turingarenad script to /usr/local/bin
```

**Comment by alerighi** [comment]
I think now the problem should be fixed, it was an error in the setup.cfg file. You need to run again `setup.py` in the `cli` directory. 

By the way, I made the new cli as the default interface, meaning that now the command `turingarena` launches the new cli. The old one for now is still available as `turingarena_legacy` command, because the new cli doesn't yet implement all the features of the old one. 

Let me know if now it works as intended, then I can close the issue.

**Comment by SartoRiccardo** [comment]
I updated everything and run `setup.py` with the command I wrote before, but it still doesn't work. This is the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/turingarenad", line 6, in <module>
    from turingarena_cli.daemon import main
ImportError: No module named 'turingarena_cli.daemon'; 'turingarena_cli' is not a package
```

**Comment by alerighi** [comment]
Ok, I think I've finally figured out what was the mistake, in the `setup.cfg` files `turingarena_cli` was indicated as a module instead of a packages. Once it was a single file and that was correct, then I transformed turingarena_cli in a directory (a python package) and that was no longer correct. 

I don't know why it was functioning on my computer, maybe because I was doing `setup.py develop`, but in theory it shouldn't have worked either.

But now in theory it should work, I tested it on another computer and before it wasn't working and now it works, so tell me if the problem is solved so I can finally close the issue.

**Comment by alerighi** [comment]
Yes, you need the package termcolor to run it. Now that I think about it, I's better if I remove that dependency completely, to get colors you can always use escape sequences, it's a little overkill to require to install a package only for that purpose. 

I will do that, and then I think I can close this issue. 

If you want to run TuringArena locally, without docker, you need to install also the packages in `turingarena_impl` and `libraries/python`, similar to `turingarena_cli` there is a `setup.py`file to execute. Keep in mind that this needs a lot of dependencies, to have an idea of what you need you can take a loot at `Dockerfile.base` and copy the pip command to install them. In Ubuntu you also need to install first `libseccomp-dev`. 

But all of this doesn't belong here in this issue, it's better if I write a document specific for local TuringArena  installation (probably I will do it tomorrow, there are other people that asked me that). 

Of course feel free to send me an email if you have difficulties installing TuringArena locally, I will be glad to help you.
